baseURL = 'https://zachmaillard.xyz/'
languageCode = 'en-us'
title = 'zachmaillard.xyz'
theme = 'hugo-theme-console'

[[params.navlinks]]
name = "about/"
url = "about/"

[[params.navlinks]]
name = "posts/"
url = "posts/"

[[params.navlinks]]
name = "highpoints/"
url = "highpoints/"
