baseURL = 'https://zachmaillard.xyz/'
languageCode = 'en-us'
title = 'zachmaillard.xyz'
theme = 'hugo-theme-console'
summaryLength = 15

enableGitInfo = true
[frontmatter]
  lastmod = ["lastmod", ":git", "date", "publishDate"]

[[params.navlinks]]
name = "about/"
url = "about/"

[[params.navlinks]]
name = "posts/"
url = "posts/"

[[params.navlinks]]
name = "highpoints/"
url = "highpoints/"
